apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  
  initContainers:
    - name: init-container
      image: busybox:latest
      command: ["sh", "-c", "mkdir -p /homework/init && wget -O /init/index.html http://example.com/index.html && mv /init/index.html /homework/init/index.html"]
      volumeMounts:
        - name: shared-volume
          mountPath: /init
          subPath: init
        - name: shared-volume
          mountPath: /homework
          subPath: homework

  containers:
    - name: main-container
      image: nginx:latest
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
          subPath: homework
      command: ["sh", "-c", "ln -sf /homework /usr/share/nginx/html && nginx -g 'daemon off;'"]
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "rm -f /homework/index.html"]

  terminationGracePeriodSeconds: 30
