apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: homework
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      
      initContainers:
        - name: init-container
          image: busybox:latest
          command: ["sh", "-c", "mkdir -p /homework/init && wget -O /init/index.html http://example.com/index.html && mv /init/index.html /homework/init/index.html"]
          volumeMounts:
            - name: shared-volume
              mountPath: /init
              subPath: init
            - name: shared-volume
              mountPath: /homework
              subPath: homework

      containers:
        - name: main-container
          image: nginx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-volume
              mountPath: /homework
              subPath: homework
          command: ["sh", "-c", "ln -sf /homework /usr/share/nginx/html && nginx -g 'daemon off;'"]
          readinessProbe:
            exec:
              command: ["test", "-f", "/homework/init/index.html"]
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "rm -f /homework/index.html"]

      terminationGracePeriodSeconds: 30
